name: Common PHP Container

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *" # 1 AM UTC

env:
  REGISTRY: ghcr.io
  FPM_NAME: devspace69/php-fpm
  XDEBUG_NAME: devspace69/php-fpm-xdebug

jobs:
  php:
    runs-on: ubuntu-latest
    concurrency:
      group: php-${{ github.workflow }}-${{ github.ref }}-${{ matrix.php_version }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355
        with:
          context: ./
          file: php.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=php-fpm-${{ matrix.php_version }}
          cache-to: type=gha,mode=max,scope=php-fpm-${{ matrix.php_version }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.FPM_NAME }}:${{ matrix.php_version }}

    strategy:
      matrix:
        php_version: ['8.0', '8.1', '8.2', '8.3']

  xdebug:
    runs-on: ubuntu-latest
    concurrency:
      group: xdebug-${{ github.workflow }}-${{ github.ref }}-${{ matrix.php_version }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355
        with:
          context: ./
          file: php.xdebug.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=php-fpm-xdebug-${{ matrix.php_version }}
          cache-to: type=gha,mode=max,scope=php-fpm-xdebug-${{ matrix.php_version }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.XDEBUG_NAME }}:${{ matrix.php_version }}

    strategy:
      matrix:
        php_version: ['8.0', '8.1', '8.2', '8.3']
